services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  inventory-service:
    build: ./inventory-service
    ports:
      - "5003:5000"
    depends_on:
      - rabbitmq