services:
  mysql:
    image: mysql:8.0
    container_name: order_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build: .
    container_name: order_service_app
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - rabbitmq
  

volumes:
  mysql_data: