services:
  mysql:
    image: mysql:8.0
    pull_policy: never
    container_name: delivery_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - delivery_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    pull_policy: never
    container_name: delivery_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  delivery-service:
    build: .
    container_name: delivery_service_app
    restart: always
    env_file:
      - .env
    ports:
      - "5005:5005"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  delivery_mysql_data: